#!/usr/bin/env bash
# =====================================================================
# error-manage-install.sh — Error Management Spec
#
# Installs the error-management guidance plus the spec-authoring guide.
#
# Quick start:
#   curl -fsSL https://raw.githubusercontent.com/alimtvnetwork/coding-guidelines-v15/main/error-manage-install.sh | bash
#   curl -fsSL https://raw.githubusercontent.com/alimtvnetwork/coding-guidelines-v15/main/error-manage-install.sh | bash -s -- --version v3.40.0
#   curl -fsSL https://raw.githubusercontent.com/alimtvnetwork/coding-guidelines-v15/main/error-manage-install.sh | bash -s -- --target ./vendor
#
# Install paths:
#   • --version vX.Y.Z → fetch error-manage.tar.gz from
#     the GitHub Release and extract with src→dest folder remapping.
#   • default          → delegate to install.sh (branch checkout).
#
# Folder mapping (src in repo → dest under target):
#   spec/01-spec-authoring-guide → spec/01-spec-authoring-guide
#   spec/03-error-manage → spec/03-error-manage
#
# Generated by scripts/generate-bundle-installers.mjs from bundles.json.
# Do not edit by hand — re-run `npm run bundles:generate` after
# editing the manifest.
# =====================================================================

set -euo pipefail

BUNDLE_NAME="error-manage"
BUNDLE_FOLDERS_SRC="spec/01-spec-authoring-guide,spec/03-error-manage"
BUNDLE_MAPPING="spec/01-spec-authoring-guide|spec/01-spec-authoring-guide spec/03-error-manage|spec/03-error-manage"
ARCHIVE_STABLE_NAME="error-manage"
RELEASE_BASE="https://github.com/alimtvnetwork/coding-guidelines-v15/releases"
INSTALLER_URL="https://raw.githubusercontent.com/alimtvnetwork/coding-guidelines-v15/main/install.sh"

VERSION=""
TARGET="$(pwd)"
FORWARD_ARGS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)        VERSION="$2"; FORWARD_ARGS+=("--version" "$2"); shift 2 ;;
    --target|--dest)  TARGET="$2"; FORWARD_ARGS+=("--dest" "$2");    shift 2 ;;
    *)                FORWARD_ARGS+=("$1");                          shift   ;;
  esac
done

echo ""
echo "════════════════════════════════════════════════════════"
echo "  Error Management Spec (bundle: ${BUNDLE_NAME})"
echo "  Target: ${TARGET}"
if [[ -n "${VERSION}" ]]; then
  echo "  Mode:   versioned archive (${ARCHIVE_STABLE_NAME}.tar.gz @ ${VERSION})"
else
  echo "  Mode:   branch checkout via install.sh"
fi
echo "════════════════════════════════════════════════════════"
echo ""

# Skip the latest-installer probe — bundle scripts pin to install.sh as-is.
export INSTALL_NO_PROBE=1

install_via_archive() {
  local archive_url="${RELEASE_BASE}/download/${VERSION}/${ARCHIVE_STABLE_NAME}.tar.gz"
  local tmp; tmp="$(mktemp -d)"
  trap "rm -rf \"${tmp}\"" EXIT

  echo "  ▸ downloading ${archive_url}"
  if ! curl -fsSL -o "${tmp}/bundle.tar.gz" "${archive_url}"; then
    echo "  ⚠️  archive fetch failed — falling back to install.sh" >&2
    install_via_installer
    return
  fi

  mkdir -p "${tmp}/extract"
  tar -xzf "${tmp}/bundle.tar.gz" -C "${tmp}/extract"

  mkdir -p "${TARGET}"
  for pair in ${BUNDLE_MAPPING}; do
    local src="${pair%|*}"
    local dest="${pair#*|}"
    if [[ ! -d "${tmp}/extract/${src}" ]]; then
      echo "  ⚠️  archive missing ${src} — skipping" >&2
      continue
    fi
    mkdir -p "${TARGET}/${dest}"
    cp -R "${tmp}/extract/${src}/." "${TARGET}/${dest}/"
    echo "  ✓ ${src} → ${TARGET}/${dest}"
  done
}

install_via_installer() {
  if command -v curl >/dev/null 2>&1; then
    curl -fsSL "${INSTALLER_URL}" | bash -s -- --folders "${BUNDLE_FOLDERS_SRC}" "${FORWARD_ARGS[@]}"
  elif command -v wget >/dev/null 2>&1; then
    wget -qO- "${INSTALLER_URL}" | bash -s -- --folders "${BUNDLE_FOLDERS_SRC}" "${FORWARD_ARGS[@]}"
  else
    echo "❌ Neither curl nor wget found. Install one and retry." >&2
    exit 1
  fi
}

if [[ -n "${VERSION}" ]]; then
  install_via_archive
else
  install_via_installer
fi

echo ""
echo "✅ ${BUNDLE_NAME} installed."
