<#
.SYNOPSIS
    Slides App + Decks — bundle installer (slides).

.DESCRIPTION
    Installs the slides Vite app and the source decks (spec-slides/).

    Install paths:
      • -Version vX.Y.Z → fetch slides.zip from the
        GitHub Release and extract with src→dest folder remapping.
      • default         → delegate to install.ps1 (branch checkout).

    Folder mapping (src in repo → dest under target):
      spec-slides → spec-slides
      slides-app → slides-app

    Generated by scripts/generate-bundle-installers.mjs from bundles.json.
    Do not edit by hand — re-run `npm run bundles:generate` after
    editing the manifest.

.EXAMPLE
    irm https://raw.githubusercontent.com/alimtvnetwork/coding-guidelines-v15/main/slides-install.ps1 | iex

.EXAMPLE
    & ([scriptblock]::Create((irm https://raw.githubusercontent.com/alimtvnetwork/coding-guidelines-v15/main/slides-install.ps1))) -Version v3.41.0 -TargetDir .\vendor
#>

param(
    [string]$Version = "",
    [Alias("Target", "Dest")]
    [string]$TargetDir = "",
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$ForwardedArgs = @()
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

$BundleName = "slides"
$BundleFoldersSrc = "spec-slides,slides-app"
$BundleMapping = "spec-slides|spec-slides,slides-app|slides-app"
$ArchiveStableName = "slides"
$ReleaseBase = "https://github.com/alimtvnetwork/coding-guidelines-v15/releases"
$InstallerUrl = "https://raw.githubusercontent.com/alimtvnetwork/coding-guidelines-v15/main/install.ps1"

if ([string]::IsNullOrEmpty($TargetDir)) { $TargetDir = (Get-Location).Path }

Write-Host ""
Write-Host "════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Slides App + Decks (bundle: $BundleName)" -ForegroundColor Cyan
Write-Host "  Target: $TargetDir" -ForegroundColor Cyan
if ($Version) {
    Write-Host "  Mode:   versioned archive ($ArchiveStableName.zip @ $Version)" -ForegroundColor Cyan
} else {
    Write-Host "  Mode:   branch checkout via install.ps1" -ForegroundColor Cyan
}
Write-Host "════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""

$env:INSTALL_NO_PROBE = "1"

function Install-ViaArchive {
    $archiveUrl = "$ReleaseBase/download/$Version/$ArchiveStableName.zip"
    $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("bundle-" + [guid]::NewGuid().ToString("N").Substring(0,8))
    New-Item -ItemType Directory -Path $tmp -Force | Out-Null
    try {
        $zipPath = Join-Path $tmp "bundle.zip"
        Write-Host "  ▸ downloading $archiveUrl"
        try {
            Invoke-WebRequest -Uri $archiveUrl -OutFile $zipPath -UseBasicParsing
        } catch {
            Write-Warning "  archive fetch failed — falling back to install.ps1: $($_.Exception.Message)"
            Install-ViaInstaller
            return
        }

        $extractDir = Join-Path $tmp "extract"
        Expand-Archive -Path $zipPath -DestinationPath $extractDir -Force

        New-Item -ItemType Directory -Path $TargetDir -Force | Out-Null
        foreach ($pair in $BundleMapping.Split(",")) {
            $parts = $pair.Split("|")
            $src = $parts[0]; $dest = $parts[1]
            $srcPath = Join-Path $extractDir $src
            if (-not (Test-Path $srcPath)) {
                Write-Warning "  archive missing $src — skipping"
                continue
            }
            $destPath = Join-Path $TargetDir $dest
            New-Item -ItemType Directory -Path $destPath -Force | Out-Null
            Copy-Item -Path (Join-Path $srcPath '*') -Destination $destPath -Recurse -Force
            Write-Host "  ✓ $src → $destPath" -ForegroundColor Green
        }
    } finally {
        Remove-Item -Path $tmp -Recurse -Force -ErrorAction SilentlyContinue
    }
}

function Install-ViaInstaller {
    $installerSource = Invoke-RestMethod -Uri $InstallerUrl -UseBasicParsing
    $installerBlock = [scriptblock]::Create($installerSource)
    $folderArray = $BundleFoldersSrc.Split(",")
    $extra = @()
    if ($Version) { $extra += @("-Version", $Version) }
    if ($TargetDir) { $extra += @("-Dest", $TargetDir) }
    & $installerBlock -Folders $folderArray @extra @ForwardedArgs
}

if ($Version) {
    Install-ViaArchive
} else {
    Install-ViaInstaller
}

Write-Host ""
Write-Host "✅ $BundleName installed." -ForegroundColor Green
